server:
  port: 7777

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/sg_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  main:
    # spring容器懒加载 默认为false
    lazy-initialization: true
    # 打开循环引用 默认为false
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:com/sangeng/mapper/xml/*.xml
  # configuration:
    # 打印sql mybatis-plus日志
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名（since 3.3.0 配置后可以忽略不配置步骤2）
      logic-delete-field: delFlag
      # 逻辑已删除值（默认为1）
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键自增 首先要求数据库字段已设置自增
      id-type: auto
